apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "spoke1-30001-vignvegx53hc.env.play.instruqt.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blue-green
            port:
              number: 8080
              
