apiVersion: v1
data:
  database-name: b3BlbnNoaWZ0
  database-password: b3BlbnNoaWZ0
  database-user: b3BlbnNoaWZ0
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2020-11-05T02:01:43Z"
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: bc326196-a0ff-44f2-980f-2546024acd9f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:database-name: {}
        f:database-password: {}
        f:database-user: {}
      f:metadata:
        f:annotations:
          .: {}
          f:template.openshift.io/expose-database_name: {}
          f:template.openshift.io/expose-password: {}
          f:template.openshift.io/expose-username: {}
        f:labels:
          .: {}
          f:template: {}
          f:template.openshift.io/template-instance-owner: {}
      f:type: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2020-11-05T02:01:43Z"
  name: postgresql
  namespace: test-app
  resourceVersion: "1367833"
  selfLink: /api/v1/namespaces/test-app/secrets/postgresql
  uid: 14f4347a-1a06-4a27-afe4-07e350cae237
type: Opaque
