apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: redhat-emea-ssa-team/hetzner-ocp4
  creationTimestamp: "2020-11-05T02:01:43Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: bc326196-a0ff-44f2-980f-2546024acd9f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-11-05T02:01:43Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:template: {}
          f:template.openshift.io/template-instance-owner: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2020-11-05T02:01:43Z"
  name: postgresql
  namespace: test-app
  resourceVersion: "1367850"
  selfLink: /api/v1/namespaces/test-app/persistentvolumeclaims/postgresql
  uid: 13950ea2-69e7-41ef-b26d-79b42ea8d88e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  volumeName: pvc-13950ea2-69e7-41ef-b26d-79b42ea8d88e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
