apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  labels:
    app: blue-green
    app.kubernetes.io/instance: blue-green
  name: blue-green
spec:
  ports:
  - name: 5555-tcp
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: blue-green
    deploymentconfig: blue-green
  sessionAffinity: None
  type: ClusterIP
